'use client'

import { useState } from 'react'
import { 
  Bot, 
  Send, 
  PencilLine, 
  FileSearch,
  ChevronDown,
  X
} from 'lucide-react'

interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: string
  mode?: 'note-taking' | 'ask' | 'explore'
}

interface ModifiedNote {
  id: string
  title: string
  changesCount: number
  timestamp: string
}

interface DiffLine {
  type: 'added' | 'removed' | 'unchanged'
  content: string
  lineNumber?: number
}

interface DiffBlock {
  type: 'added' | 'removed' | 'unchanged'
  oldHtml?: string
  newHtml?: string
  html?: string
}

interface Chat {
  id: string
  title: string
  messages: ChatMessage[]
  createdAt: string
  updatedAt: string
  folderId?: string
}

interface ChatFolder {
  id: string
  name: string
  chats: Chat[]
}

interface ChatTab {
  id: string
  chatId: string | null
}

interface ChatProps {
  activeChat: string | null
  chatFolders: ChatFolder[]
  unorganizedChats: Chat[]
  selectedModel: string
  openTabs: ChatTab[]
  activeTabId: string | null
  onUpdateChatFolders: (folders: ChatFolder[]) => void
  onUpdateUnorganizedChats: (chats: Chat[]) => void
  onSetSelectedModel: (model: string) => void
  onOpenTab: (chatId: string | null) => void
  onCloseTab: (tabId: string) => void
  onSwitchTab: (tabId: string) => void
  onCreateNewChat: () => void
  onMoveChatToFolder: (chatId: string, folderId: string | null) => void
  onCreateFolder: (folderName: string) => void
}

export function ChatComponent({
  activeChat,
  chatFolders,
  unorganizedChats,
  selectedModel,
  openTabs,
  activeTabId,
  onUpdateChatFolders,
  onUpdateUnorganizedChats,
  onSetSelectedModel,
  onOpenTab,
  onCloseTab,
  onSwitchTab,
  onCreateNewChat,
  onMoveChatToFolder,
  onCreateFolder
}: ChatProps) {
  const [chatInput, setChatInput] = useState('')
  const [chatMode, setChatMode] = useState<'note-taking' | 'ask' | 'explore'>('explore')
  const [showModeDropdown, setShowModeDropdown] = useState(false)
  const [modifiedNotes, setModifiedNotes] = useState<ModifiedNote[]>([
    // Demo data - shows by default
    {
      id: 'demo-1',
      title: 'AI Agents Overview',
      changesCount: 5,
      timestamp: new Date().toLocaleTimeString()
    },
    {
      id: 'demo-2',
      title: 'Next.js Best Practices',
      changesCount: 3,
      timestamp: new Date().toLocaleTimeString()
    }
  ])
  const [showModifiedNotes, setShowModifiedNotes] = useState(true)
  const [selectedNoteForDiff, setSelectedNoteForDiff] = useState<string | null>(null)
  const [diffViewMode, setDiffViewMode] = useState<'new' | 'old' | 'diff'>('new')

  // Mock unified HTML document with inline diff highlights
  const getUnifiedHtmlWithDiff = (noteId: string, mode: 'new' | 'old' | 'diff'): string => {
    // In a real implementation, this would be generated by comparing old and new HTML
    // For demo, we're showing a document with inline highlights
    
    if (mode === 'new') {
      // Show new version with only added parts highlighted
      return `<div class="prose max-w-none">
        <h2>AI Agents Overview</h2>
        <p>AI agents are autonomous systems that can perceive their environment, make decisions, and take actions to achieve specific goals.</p>
        
        <h3>Key Characteristics</h3>
        <ul>
          <li><strong>Autonomy:</strong> <span class="diff-added">Full independent operation without any</span> human intervention</li>
          <li><strong>Reactivity:</strong> Respond to changes in their environment<span class="diff-added"> in real-time</span></li>
          <li class="diff-added"><strong>Proactivity:</strong> Take initiative to achieve goals</li>
          <li class="diff-added"><strong>Social Ability:</strong> Interact with other agents and humans</li>
        </ul>
        
        <blockquote class="border-l-4 border-purple-500 pl-4 italic bg-purple-50 p-4 rounded">
          "An agent is anything that can perceive its environment through sensors and act upon that environment through actuators." - Russell & Norvig
        </blockquote>
        
        <div class="diff-added bg-green-50 p-4 rounded-lg my-4 border-l-4 border-green-500">
          <h4 class="font-semibold text-green-900 mb-2">New Section: Agent Types</h4>
          <p class="text-green-800">Modern AI agents can be classified into several categories based on their capabilities and decision-making processes.</p>
          <ul class="text-green-800 mt-2">
            <li>Simple Reflex Agents</li>
            <li>Model-Based Agents</li>
            <li>Goal-Based Agents</li>
            <li>Utility-Based Agents</li>
          </ul>
        </div>
        
        <pre class="bg-gray-900 p-4 rounded-lg"><code class="text-green-400">// Advanced agent example with learning
class Agent {
  constructor() {
    this.memory = [];
    this.learningRate = 0.1;
  }
  
  decide(environment) {
    const action = this.selectBestAction(environment);
    this.learn(environment, action);
    return action;
  }
  
  learn(env, action) {
    this.memory.push({ env, action });
    this.updateModel();
  }
}</code></pre>
      </div>`
    } else if (mode === 'old') {
      // Show old version with only removed parts highlighted
      return `<div class="prose max-w-none">
        <h2>AI Agents Overview</h2>
        <p>AI agents are autonomous systems that can perceive their environment, make decisions, and take actions to achieve specific goals.</p>
        
        <h3>Key Characteristics</h3>
        <ul>
          <li><strong>Autonomy:</strong> <span class="diff-removed">Operate without direct</span> human intervention</li>
          <li><strong>Reactivity:</strong> Respond to changes in their environment</li>
        </ul>
        
        <blockquote class="border-l-4 border-purple-500 pl-4 italic bg-purple-50 p-4 rounded">
          "An agent is anything that can perceive its environment through sensors and act upon that environment through actuators." - Russell & Norvig
        </blockquote>
        
        <pre class="diff-removed bg-gray-100 p-4 rounded-lg"><code>// Simple agent example
if (temperature > 25) {
  turnOnAC();
}</code></pre>
      </div>`
    } else {
      // Diff mode - show both added and removed inline
      return `<div class="prose max-w-none">
        <h2>AI Agents Overview</h2>
        <p>AI agents are autonomous systems that can perceive their environment, make decisions, and take actions to achieve specific goals.</p>
        
        <h3>Key Characteristics</h3>
        <ul>
          <li><strong>Autonomy:</strong> <span class="diff-removed">Operate without direct</span><span class="diff-added">Full independent operation without any</span> human intervention</li>
          <li><strong>Reactivity:</strong> Respond to changes in their environment<span class="diff-added"> in real-time</span></li>
          <li class="diff-added"><strong>Proactivity:</strong> Take initiative to achieve goals</li>
          <li class="diff-added"><strong>Social Ability:</strong> Interact with other agents and humans</li>
        </ul>
        
        <blockquote class="border-l-4 border-purple-500 pl-4 italic bg-purple-50 p-4 rounded">
          "An agent is anything that can perceive its environment through sensors and act upon that environment through actuators." - Russell & Norvig
        </blockquote>
        
        <div class="diff-added bg-green-50 p-4 rounded-lg my-4 border-l-4 border-green-500">
          <h4 class="font-semibold text-green-900 mb-2">New Section: Agent Types</h4>
          <p class="text-green-800">Modern AI agents can be classified into several categories based on their capabilities and decision-making processes.</p>
          <ul class="text-green-800 mt-2">
            <li>Simple Reflex Agents</li>
            <li>Model-Based Agents</li>
            <li>Goal-Based Agents</li>
            <li>Utility-Based Agents</li>
          </ul>
        </div>
        
        <div class="diff-removed">
          <pre class="bg-gray-100 p-4 rounded-lg"><code>// Simple agent example
if (temperature > 25) {
  turnOnAC();
}</code></pre>
        </div>
        
        <div class="diff-added">
          <pre class="bg-gray-900 p-4 rounded-lg"><code class="text-green-400">// Advanced agent example with learning
class Agent {
  constructor() {
    this.memory = [];
    this.learningRate = 0.1;
  }
  
  decide(environment) {
    const action = this.selectBestAction(environment);
    this.learn(environment, action);
    return action;
  }
  
  learn(env, action) {
    this.memory.push({ env, action });
    this.updateModel();
  }
}</code></pre>
        </div>
      </div>`
    }
  }

  const currentChat = [...chatFolders.flatMap(f => f.chats), ...unorganizedChats].find(c => c.id === activeChat)

  const handleSendMessage = () => {
    if (!chatInput.trim() || !activeChat) return

    const newMessage: ChatMessage = {
      id: `msg-${Date.now()}`,
      role: 'user',
      content: chatInput,
      timestamp: new Date().toLocaleString(),
      mode: chatMode
    }

    // Update the chat with new message
    const updateChat = (chat: Chat) => {
      if (chat.id === activeChat) {
        return {
          ...chat,
          messages: [...chat.messages, newMessage],
          title: chat.messages.length === 0 ? chatInput.slice(0, 50) : chat.title,
          updatedAt: new Date().toISOString().split('T')[0]
        }
      }
      return chat
    }

    onUpdateChatFolders(chatFolders.map(folder => ({
      ...folder,
      chats: folder.chats.map(updateChat)
    })))
    onUpdateUnorganizedChats(unorganizedChats.map(updateChat))
    setChatInput('')

    // Simulate AI response after a short delay
    setTimeout(() => {
      let responseContent = ''
      
      if (chatMode === 'note-taking') {
        responseContent = `**Note Taking Mode Active**\n\nI'll help you modify your notes. Based on your request: "${newMessage.content}"\n\nI would:\n1. Analyze the requested changes\n2. Update the relevant note sections\n3. Maintain proper formatting and structure\n4. Preserve your existing content where needed\n\nThis is a demo. In a production environment, I would apply these changes directly to your notes using ${selectedModel}.`
        
        // Simulate adding modified notes
        const newModifiedNote: ModifiedNote = {
          id: `note-${Date.now()}`,
          title: 'AI Agents Overview', // Demo note title
          changesCount: Math.floor(Math.random() * 10) + 1,
          timestamp: new Date().toLocaleTimeString()
        }
        setModifiedNotes(prev => {
          // Check if note already exists, update it
          const existing = prev.find(n => n.title === newModifiedNote.title)
          if (existing) {
            return prev.map(n => 
              n.title === newModifiedNote.title 
                ? { ...n, changesCount: n.changesCount + newModifiedNote.changesCount, timestamp: newModifiedNote.timestamp }
                : n
            )
          }
          return [...prev, newModifiedNote]
        })
      } else if (chatMode === 'ask') {
        responseContent = `**Ask Mode Active**\n\nSearching your knowledge base for: "${newMessage.content}"\n\nBased on your notes, here's what I found:\n\n• Found references in "AI Agents" space\n• Found references in "Next.js" space\n\nThis is a demo response using ${selectedModel}. In a real implementation, I would:\n1. Search through all your notes\n2. Find relevant information\n3. Provide accurate answers with citations\n4. Suggest related topics`
      } else {
        responseContent = `**Explore Mode Active**\n\nSearching the web and my general knowledge for: "${newMessage.content}"\n\nHere's what I found:\n\n• Researching latest information from across the web\n• Accessing general knowledge and external resources\n• Compiling comprehensive insights\n\nThis is a demo response using ${selectedModel}. In a production environment, I would:\n1. Search the internet for current information\n2. Use my trained knowledge base\n3. Provide well-researched answers with sources\n4. Offer broader context beyond your personal notes`
      }

      const aiResponse: ChatMessage = {
        id: `msg-${Date.now()}`,
        role: 'assistant',
        content: responseContent,
        timestamp: new Date().toLocaleString(),
        mode: chatMode
      }

      const updateWithAI = (chat: Chat) => {
        if (chat.id === activeChat) {
          return {
            ...chat,
            messages: [...chat.messages, aiResponse],
            updatedAt: new Date().toISOString().split('T')[0]
          }
        }
        return chat
      }

      onUpdateChatFolders(chatFolders.map(folder => ({
        ...folder,
        chats: folder.chats.map(updateWithAI)
      })))
      onUpdateUnorganizedChats(unorganizedChats.map(updateWithAI))
    }, 1000)
  }

  if (!currentChat) {
    return (
      <div className="flex items-center justify-center h-full p-8">
        <div className="text-center">
          <Bot className="h-16 w-16 text-gray-400 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-gray-900 mb-2">No Chat Selected</h2>
          <p className="text-gray-600">
            Select a chat from the sidebar or create a new one
          </p>
        </div>
      </div>
    )
  }

  // Get unified HTML with inline diff highlights
  const getUnifiedDiffHtml = (noteId: string): string => {
    return getUnifiedHtmlWithDiff(noteId, diffViewMode)
  }

  return (
    <div className="flex h-full">
      {/* Document Viewer - Left Side (when note selected) - Takes more space */}
      {selectedNoteForDiff && (
        <div className="w-[70%] border-r border-gray-200 flex flex-col bg-gray-50">
          {/* Header with Tabs */}
          <div className="border-b border-gray-200 bg-white">
            {/* Title Bar */}
            <div className="px-3 py-2 flex items-center justify-between border-b border-gray-100">
              <div className="flex items-center gap-2">
                <PencilLine className="h-3.5 w-3.5 text-purple-600" />
                <span className="font-semibold text-sm text-gray-900">
                  {modifiedNotes.find(n => n.id === selectedNoteForDiff)?.title}
                </span>
                <span className="text-xs text-gray-500">
                  ({modifiedNotes.find(n => n.id === selectedNoteForDiff)?.changesCount} changes)
                </span>
              </div>
              <button
                onClick={() => {
                  setSelectedNoteForDiff(null)
                  setDiffViewMode('new')
                }}
                className="p-1 hover:bg-gray-100 rounded transition-colors"
                title="Close"
              >
                <X className="h-3.5 w-3.5 text-gray-600" />
              </button>
            </div>

            {/* Tabs */}
            <div className="flex items-center gap-1 px-3 py-1">
              <button
                onClick={() => setDiffViewMode('new')}
                className={`px-3 py-1 text-xs font-medium rounded transition-colors ${
                  diffViewMode === 'new'
                    ? 'bg-green-100 text-green-700'
                    : 'text-gray-600 hover:bg-gray-100'
                }`}
              >
                New Version
              </button>
              <button
                onClick={() => setDiffViewMode('old')}
                className={`px-3 py-1 text-xs font-medium rounded transition-colors ${
                  diffViewMode === 'old'
                    ? 'bg-red-100 text-red-700'
                    : 'text-gray-600 hover:bg-gray-100'
                }`}
              >
                Old Version
              </button>
              <button
                onClick={() => setDiffViewMode('diff')}
                className={`px-3 py-1 text-xs font-medium rounded transition-colors ${
                  diffViewMode === 'diff'
                    ? 'bg-blue-100 text-blue-700'
                    : 'text-gray-600 hover:bg-gray-100'
                }`}
              >
                All Changes
              </button>
            </div>
          </div>

          {/* Document Content - Unified HTML Diff Viewer with Inline Highlights */}
          <div className="flex-1 overflow-y-auto p-4">
            <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
              <div 
                className="prose prose-sm max-w-none"
                dangerouslySetInnerHTML={{ __html: getUnifiedDiffHtml(selectedNoteForDiff) }}
              />
            </div>
          </div>
        </div>
      )}

      {/* Chat Area - Right Side (or full width) - Takes less space when split */}
      <div className={`flex flex-col ${selectedNoteForDiff ? 'w-[30%]' : 'w-full'} h-full`}>
        {/* Messages Area */}
        <div className="flex-1 overflow-y-auto p-6">
        {currentChat.messages.length === 0 ? (
          <div className="flex items-center justify-center h-full">
            <div className="text-center max-w-md">
              <Bot className="h-16 w-16 text-purple-600 mx-auto mb-4" />
              <h2 className="text-2xl font-bold text-gray-900 mb-2">Start a Conversation</h2>
              <p className="text-gray-600 mb-4">
                {chatMode === 'note-taking' 
                  ? `I'm in Note Taking mode. Tell me what changes you'd like to make to your notes.`
                  : chatMode === 'ask'
                  ? `I'm in Ask mode. Ask me questions about your notes and I'll search for answers.`
                  : `I'm in Explore mode. Ask me anything and I'll search the web and use my general knowledge.`
                }
              </p>
              <div className="grid grid-cols-1 gap-2 text-left">
                {(chatMode === 'note-taking' ? [
                  'Add a new section about React Server Components',
                  'Update my AI Agents note with latest best practices',
                  'Create a new page about TypeScript generics',
                  'Restructure my Next.js notes'
                ] : chatMode === 'ask' ? [
                  'What are the key characteristics of AI agents?',
                  'How does Server-Side Rendering work in Next.js?',
                  'Show me notes about React hooks',
                  'Find information about performance optimization'
                ] : [
                  'What are the latest trends in artificial intelligence?',
                  'Explain how quantum computing works',
                  'What is the difference between REST and GraphQL?',
                  'Tell me about recent advances in web development'
                ]).map((suggestion, idx) => (
                  <button
                    key={idx}
                    onClick={() => setChatInput(suggestion)}
                    className="p-3 text-sm bg-purple-50 hover:bg-purple-100 text-purple-700 rounded-lg transition-colors text-left"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <div className="max-w-4xl mx-auto space-y-6">
            {currentChat.messages.map((message) => (
              <div
                key={message.id}
                className={`flex gap-4 ${
                  message.role === 'user' ? 'justify-end' : 'justify-start'
                }`}
              >
                {message.role === 'assistant' && (
                  <div className="w-8 h-8 rounded-full bg-purple-600 flex items-center justify-center flex-shrink-0">
                    <Bot className="h-5 w-5 text-white" />
                  </div>
                )}
                <div
                  className={`max-w-[70%] rounded-2xl px-4 py-3 ${
                    message.role === 'user'
                      ? 'bg-purple-600 text-white'
                      : 'bg-gray-100 text-gray-900'
                  }`}
                >
                  {/* Mode indicator badge */}
                  {message.mode && (
                    <div className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium mb-2 ${
                      message.role === 'user'
                        ? 'bg-purple-700 text-purple-100'
                        : 'bg-purple-100 text-purple-700'
                    }`}>
                      {message.mode === 'note-taking' ? (
                        <>
                          <PencilLine className="h-3 w-3" />
                          <span>Note Taking</span>
                        </>
                      ) : message.mode === 'ask' ? (
                        <>
                          <FileSearch className="h-3 w-3" />
                          <span>Ask</span>
                        </>
                      ) : (
                        <>
                          <span>🌐</span>
                          <span>Explore</span>
                        </>
                      )}
                    </div>
                  )}
                  <p className="text-sm whitespace-pre-wrap">{message.content}</p>
                  <p className={`text-xs mt-2 ${
                    message.role === 'user' ? 'text-purple-200' : 'text-gray-500'
                  }`}>
                    {message.timestamp}
                  </p>
                </div>
                {message.role === 'user' && (
                  <div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center flex-shrink-0 text-white font-semibold text-sm">
                    U
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Modified Notes Section - Vertical List at bottom */}
      {modifiedNotes.length > 0 && (
        <div className="border-t border-gray-200 bg-gray-50">
          <div className="max-w-4xl mx-auto">
            {/* Header with collapse button and clear */}
            <div className="flex items-center justify-between px-3 py-1.5">
              <button
                onClick={() => setShowModifiedNotes(!showModifiedNotes)}
                className="flex items-center gap-1.5 hover:bg-gray-100 rounded px-2 py-0.5 transition-colors"
              >
                <ChevronDown className={`h-3 w-3 text-gray-600 transition-transform ${showModifiedNotes ? '' : '-rotate-90'}`} />
                <span className="text-xs font-medium text-gray-700">
                  {modifiedNotes.length} {modifiedNotes.length === 1 ? 'File' : 'Files'}
                </span>
              </button>
              
              {showModifiedNotes && (
                <button
                  onClick={() => setModifiedNotes([])}
                  className="text-xs text-gray-600 hover:text-gray-900 font-medium hover:bg-gray-100 px-2 py-0.5 rounded"
                >
                  Clear All
                </button>
              )}
            </div>
            
            {/* Files in vertical list */}
            {showModifiedNotes && (
              <div className="px-3 pb-2 space-y-1 max-h-32 overflow-y-auto scrollbar-thin">
                {modifiedNotes.map((note) => (
                  <button
                    key={note.id}
                    onClick={() => setSelectedNoteForDiff(selectedNoteForDiff === note.id ? null : note.id)}
                    className={`w-full flex items-center gap-1.5 px-2 py-1 rounded border text-xs transition-colors ${
                      selectedNoteForDiff === note.id
                        ? 'bg-purple-100 border-purple-400 text-purple-900'
                        : 'bg-white border-gray-300 hover:bg-gray-50'
                    }`}
                  >
                    <PencilLine className="h-3 w-3 text-gray-500 flex-shrink-0" />
                    <span className="font-medium text-gray-900 flex-1 text-left truncate">
                      {note.title}
                    </span>
                    <span className="text-gray-400 flex-shrink-0">→</span>
                    <span className="text-gray-600 whitespace-nowrap flex-shrink-0">
                      {note.changesCount} {note.changesCount === 1 ? 'Line' : 'Lines'} Modified
                    </span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Input Area - Optimized Compact Design */}
      <div className="border-t border-gray-200 bg-white px-4 py-2">
        <div className="max-w-4xl mx-auto">
          {/* Compact Input Container */}
          <div className="flex items-end gap-2 mb-2">
            {/* Main Input Area with Integrated Send Button */}
            <div className="flex-1 relative">
              <textarea
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault()
                    handleSendMessage()
                  }
                }}
                placeholder={
                  chatMode === 'note-taking'
                    ? 'Describe changes to your notes...'
                    : chatMode === 'ask'
                    ? 'Ask about your notes...'
                    : 'Ask anything...'
                }
                className="w-full pl-3 pr-10 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent outline-none resize-none text-sm"
                rows={1}
                style={{ minHeight: '38px', maxHeight: '150px' }}
                onInput={(e) => {
                  const target = e.target as HTMLTextAreaElement
                  target.style.height = 'auto'
                  target.style.height = Math.min(target.scrollHeight, 150) + 'px'
                }}
              />
              {/* Send Button Inside Input */}
              <button
                onClick={handleSendMessage}
                disabled={!chatInput.trim()}
                className="absolute right-2 bottom-2 p-1.5 bg-purple-600 text-white rounded-md hover:bg-purple-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed disabled:bg-gray-300"
                title="Send message (Enter)"
              >
                <Send className="h-4 w-4" />
              </button>
            </div>
          </div>

          {/* Compact Controls Row */}
          <div className="flex items-center gap-2 text-xs">
            {/* Mode Selector - Compact */}
            <div className="relative">
              <button
                onClick={() => setShowModeDropdown(!showModeDropdown)}
                className="px-2 py-1 text-xs border border-gray-300 rounded-md bg-white hover:bg-gray-50 focus:ring-1 focus:ring-purple-500 outline-none cursor-pointer flex items-center gap-1"
                title="Chat Mode"
              >
                <span>{chatMode === 'explore' ? '🌐 Explore' : chatMode === 'ask' ? '🔍 Ask' : '📝 Note'}</span>
                <ChevronDown className={`h-3 w-3 text-gray-500 transition-transform ${showModeDropdown ? 'rotate-180' : ''}`} />
              </button>
              
              {/* Dropdown Menu */}
              {showModeDropdown && (
                <>
                  <div 
                    className="fixed inset-0 z-40" 
                    onClick={() => setShowModeDropdown(false)}
                  />
                  <div className="absolute bottom-full left-0 mb-1 w-48 bg-white border border-gray-300 rounded-lg shadow-lg z-50">
                    <button
                      onClick={() => {
                        setChatMode('explore')
                        setShowModeDropdown(false)
                      }}
                      className={`w-full px-3 py-2 text-xs text-left hover:bg-purple-50 transition-colors ${
                        chatMode === 'explore' ? 'bg-purple-100 text-purple-700 font-medium' : 'text-gray-700'
                      }`}
                    >
                      🌐 Explore - Web & general knowledge
                    </button>
                    <button
                      onClick={() => {
                        setChatMode('note-taking')
                        setShowModeDropdown(false)
                      }}
                      className={`w-full px-3 py-2 text-xs text-left hover:bg-purple-50 transition-colors ${
                        chatMode === 'note-taking' ? 'bg-purple-100 text-purple-700 font-medium' : 'text-gray-700'
                      }`}
                    >
                      📝 Note Taking - Edit notes
                    </button>
                    <button
                      onClick={() => {
                        setChatMode('ask')
                        setShowModeDropdown(false)
                      }}
                      className={`w-full px-3 py-2 text-xs text-left hover:bg-purple-50 transition-colors ${
                        chatMode === 'ask' ? 'bg-purple-100 text-purple-700 font-medium' : 'text-gray-700'
                      }`}
                    >
                      🔍 Ask - Search your notes
                    </button>
                  </div>
                </>
              )}
            </div>

            {/* Model Selector - Compact */}
            <select
              value={selectedModel}
              onChange={(e) => onSetSelectedModel(e.target.value)}
              className="px-2 py-1 text-xs border border-gray-300 rounded-md bg-white hover:bg-gray-50 focus:ring-1 focus:ring-purple-500 outline-none cursor-pointer"
              title="AI Model"
            >
              <option value="gpt-4">GPT-4</option>
              <option value="gpt-4-turbo">GPT-4 Turbo</option>
              <option value="gpt-3.5-turbo">GPT-3.5 Turbo</option>
              <option value="claude-3-opus">Claude 3 Opus</option>
              <option value="claude-3-sonnet">Claude 3 Sonnet</option>
              <option value="claude-3-haiku">Claude 3 Haiku</option>
              <option value="gemini-pro">Gemini Pro</option>
            </select>

            {/* Hint Text */}
            <span className="text-gray-400 ml-auto">Press Enter to send, Shift+Enter for new line</span>
          </div>
        </div>
      </div>
      </div>
    </div>
  )
}

